kind: project
metadata:
  name: mlrun-run-notifications
spec:
  functions:
  - url: get_data.py
    name: get-data
    kind: job
    image: mlrun/mlrun
  - url: train.py
    name: train
    kind: job
    image: mlrun/mlrun
  - url: hub://v2_model_server
    name: serving
  workflows:
  - path: training_pipeline.py
    name: main
  artifacts: []
  source: git://github.com/igz-us-sales/mlrun-run-notifications.git#refs/heads/master
  origin_url: git://github.com/igz-us-sales/mlrun-run-notifications.git#refs/heads/master
  desired_state: online
